### ISSUE TITLE
Frontend connect localhost with dev server

### ISSUE THREAD

**Issue by viiiprock** [chryb/graphql-apollo-boilerplate#1]
Thanks @chryb  for your boilerplate,
I'm very new with webpack stuff, I need to work with e.g `http://localhost:8080/graphql` endpoint for testing my React front-end in some cases. 
From the client

```js
import { createHttpLink } from 'apollo-link-http'
const httpLink = createHttpLink({
  uri: 'http://localhost:8000/api',
  credentials: 'same-origin'
})
```
All requests & responses work well with **Insomnia** (graphiql is well off course ), but with frontend (is local too, with port 3000)  is not.
XHR log

```
Request URL:http://localhost:8080/api
Request Method:POST
Status Code:400 Bad Request
Remote Address:[::1]:8080
Referrer Policy:no-referrer-when-downgrade
```

Thanks for your reply,

**Comment by viiiprock** [comment]
**Update**:
I config webpack dev server with this:
```js
    devServer: {
      contentBase: path.join(__dirname, "dist"),
      compress: true,
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Methods": "GET, POST, PUT, DELETE, PATCH, OPTIONS",
        "Access-Control-Allow-Headers": "X-Requested-With, content-type, Authorization"
      },
      port: 9000
    },
```

And the response is 200:
```
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
Access-Control-Allow-Headers: X-Requested-With, content-type, Authorization
Allow: GET,HEAD
Content-Type: text/html; charset=utf-8
Content-Length: 8
ETag: W/"8-ZRAf8oNBS3Bjb/SU2GYZCmbtmXg"
Vary: Accept-Encoding
Date: Wed, 06 Dec 2017 08:04:39 GMT
Connection: keep-alive
```
But I got error at client (but I bet this must be my fault at webpack config)
`Unhandled (in react-apollo) Error: Network error: Unexpected token < in JSON at position 0`

**Comment by biering** [comment]
Hi @viiiprock, sorry for the late response but I was a bit busy the last few days. Did you found a solution for your problem?

**Comment by viiiprock** [comment]
yes, I have mistaken while migrating from mine to your boilerplate (queries a null resolver). Actually, create-react-app had problem at proxy local IPv6  before but they did fixed it :)  
Your boilerplate now works like a charm, thanks @chryb

**Comment by biering** [comment]
@viiiprock Ok. That's great to hear!
